[FEAT]
Team-Plu/Plu-Server pull request #30
Opened 2024-03-03 17:22 UTC by PgmJun

## ✒️ 관련 이슈번호

- Closes #28 

## 🔑 Key Changes

1. 질문에 대한 답변 조회 기능 구현

## 📸 Screenshot

## 📢 To Reviewers
- `LikeRepository`에 `JpaRepository<Member, Repository>` 로 되어있는데, 이 부분을 바로 다음 PR에서 처리했습니다.
이 부분에 대해서는 신경 안쓰셔도 될 것 같습니다!

2024-03-05 11:36 UTC, orijoon98 commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/answer/Answer.kt
> +        var content: String,
인텔리제이 기본 포매터인가용?

2024-03-05 11:36 UTC, orijoon98 commented on plu-api/src/main/kotlin/com/th/plu/api/service/answer/AnswerService.kt
> +    }
그 나만보기 설정한 답변 같은 경우에는 본인이 작성한 글인지 validation 과정이 필요할 것 같아요.

2024-03-05 11:36 UTC, orijoon98 commented
추가로 대환이형이 적용한 entity 에 _id 패턴이나, retriever, explorer 등 네이밍 컨벤션도 맞춰서 머지하면 좋을 것 같습니다.

2024-03-06 17:32 UTC, sookyungg requested changes

2024-03-06 17:32 UTC, sookyungg commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/answer/Answer.kt
> +        var content: String,
인텔리제이 기본 포매터+Tap size 4칸 으로 설정해주면 될 것 같아요!

2024-03-06 17:32 UTC, sookyungg commented on plu-api/src/main/kotlin/com/th/plu/api/controller/answer/AnswerController.kt
> +    @Operation(summary = "답변 조회")
명세서와 동일하게 [인증] 질문 답변 조회 로 바꿔주면 좋을 것 같습니다!

2024-03-06 17:33 UTC, sookyungg approved these changes

2024-03-08 05:32 UTC, PgmJun commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/answer/Answer.kt
> +        var content: String,
아 기본 포매터로 가는군요! 확인이엽!

2024-03-08 05:32 UTC, PgmJun commented on plu-api/src/main/kotlin/com/th/plu/api/controller/answer/AnswerController.kt
> +    @Operation(summary = "답변 조회")
체킹 감사합니다:)

2024-03-09 08:57 UTC, PgmJun commented
> 추가로 대환이형이 적용한 entity 에 _id 패턴이나, retriever, explorer 등 네이밍 컨벤션도 맞춰서 머지하면 좋을 것 같습니다.

하나의 기능인데 지금 api가 너무 많아져서 다 끝나고 수정하겠습니다..!
explorer validator 등은 최대한 적용해볼게용

2024-03-09 08:57 UTC, PgmJun commented on plu-api/src/main/kotlin/com/th/plu/api/service/answer/AnswerService.kt
> +    }
적용 완료했습니다:) 머지할게요!

2024-03-09 08:59 UTC, merged