⚡️: fix Answer, Question 관련 오류 수정 ver.1 #38
Team-Plu/Plu-Server pull request #39
Opened 2024-04-05 18:38 UTC by sookyungg

## ✒️ 관련 이슈번호

- Closes #38 

## 🔑 Key Changes

1. 내용
    - 같은 부분 작업내용이 문제가 생긴것 같아요..!! 
    - 네이밍도 비슷해서 겹치는 부분 최대한 수정 해보았는데 확인 부탁 드려요!
    -  TODO: 밑에 첨부한 보시면 겹치고 있어요! 오늘의 질문 조회 관련이 작동이 조금 이상하게 됩니답.. 

## 📸 Screenshot
![image](https://github.com/Team-Plu/Plu-Server/assets/64000241/da56a39d-0af6-4eae-9142-ef583c3bcb3e)

## 📢 To Reviewers
-

2024-04-12 09:07 UTC, PgmJun requested changes
리뷰 환영 및 반영 부탁드립니다!

2024-04-12 09:07 UTC, PgmJun commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/question/explorer/QuestionExplorer.kt
> +        questionRepository.findById(id).orElse(null)
null을 직접 사용하는 것보다 orElseThrow 구문 사용은 어떠신가요??

2024-04-12 09:07 UTC, PgmJun commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/answer/Answer.kt
> +    }
디미터 법칙을 지키는 코드네요:)

2024-04-12 09:07 UTC, PgmJun commented on plu-api/src/main/kotlin/com/th/plu/api/service/answer/AnswerService.kt
>          val todayQuestion = questionExplorer.findTodayQuestion()
여기 `@Transactional(readOnly=true)` 가 없는데 붙여주면 좋을 것 같아요!
제가 실수한 것 같아요..!

2024-04-12 13:50 UTC, sookyungg commented on plu-api/src/main/kotlin/com/th/plu/api/service/answer/AnswerService.kt
>          val todayQuestion = questionExplorer.findTodayQuestion()
반영 완료 해두었습니다!

2024-04-12 13:52 UTC, sookyungg commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/question/explorer/QuestionExplorer.kt
> +        questionRepository.findById(id).orElse(null)
kotlin 의 null 안전성으로 처리하는 방향으로 수정해 볼 수 있을 것 같은데, 
일단 orElseThrow로 수정해놓고 조금 알아봐볼게용

2024-04-14 05:26 UTC, daehwan2da requested changes
우리 LocalDateTime 으로 시간 핸들링하는게 많은것같은데,  
이거 서버랑 디비 기준으로 시간이 KST 로 안될 수 있어서 시간 파싱 처리는 한곳에서 하도록 개선이 필요해보이는데요, 이 작업 task 따로 잡아서 내가 해둘까요?

- 문제점
  - 서비스중에 기대하기는 한국 시간으로 기대하지만 별도 시간에 대한 관리처가 없어서 이상한 시간으로 처리되어질 수 있음

2024-04-14 05:26 UTC, daehwan2da commented on plu-domain/src/main/kotlin/com/th/plu/domain/domain/answer/repository/AnswerRepositoryImpl.kt
> +            .fetchOne()!!
`!!` 는 빼야할것같은데요 
` fun findPublicAnswersCountByQuestionId(questionId: Long): Long?` 이렇게 바꿔야할듯

2024-04-15 11:39 UTC, merged